2023-091-090019 | 1163 | DEBUG | light.py:12 | action | {'result': {'device_id': '80221F2A8BED0E3122B7E73B88B110F71F8C4676', 'fw_ver': '1.1.6 Build 221114 Rel.203339', 'hw_ver': '1.0', 'type': 'SMART.TAPOPLUG', 'model': 'P110', 'mac': '14-EB-B6-0A-4F-D2', 'hw_id': 'C6F5BD033F018D8B734D81679BCF9F75', 'fw_id': '00000000000000000000000000000000', 'oem_id': 'DE16B0A9B7DC121F195BAA6CD15EB4A1', 'ip': '192.168.1.192', 'time_diff': 600, 'ssid': 'V2lGaS0zMjY2', 'rssi': -72, 'signal_level': 1, 'latitude': 0, 'longitude': 0, 'lang': '', 'avatar': 'plug', 'region': 'Australia/Melbourne', 'specs': '', 'nickname': 'U21hcnQgUGx1Zw==', 'has_set_location_info': False, 'device_on': False, 'on_time': 0, 'default_states': {'type': 'last_states', 'state': {}}, 'overheated': False, 'power_protection_status': 'normal'}, 'error_code': 0}
2023-109-195632 | 577 | ERROR | l530.py:24 | _authenticate | L530 Authentication Error (L1): module 'PyP100.PyL530' has no attribute 'P110'
